packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@orpc/client': ^1.0.3
  '@orpc/contract': ^1.0.3
  '@orpc/server': ^1.0.3
  '@orpc/react-query': ^1.0.3
  '@tailwindcss/vite': ^4.1.4
  eslint: ^9.25.1
  tailwindcss: ^4.1.4
  tsup: ^8.4.0
  vite: ^6.3.2
  vitest: ^3.1.2
  zod: ^3.24.3
