packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@orpc/client': ^1.0.0-beta.5
  '@orpc/contract': ^1.0.0-beta.5
  '@orpc/server': ^1.0.0-beta.5
  '@orpc/react-query': ^1.0.0-beta.5
  eslint: ^9.23.0
  tsup: ^8.4.0
  vite: ^6.2.5
  vitest: ^3.1.1
  zod: ^3.24.2
