packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@orpc/client": ^1.10.3
  "@orpc/contract": ^1.10.3
  "@orpc/openapi": ^1.10.3
  "@orpc/react-query": ^1.10.3
  "@orpc/server": ^1.10.3
  "@tailwindcss/vite": ^4.1.16
  eslint: ^9.39.1
  tailwindcss: ^4.1.16
  tsup: ^8.5.0
  vite: ^7.1.12
  vitest: ^4.0.6
  zod: ^4.1.12
