# Extended from https://github.com/antfu/starter-ts/blob/main/.github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  linting-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Cache Turborepo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.ref_name }}
          restore-keys: |
            turbo-${{ runner.os }}-main
            turbo-${{ runner.os }}

      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run check-types
      - run: pnpm run build
      - run: pnpm run test
