name: Playwright Tests
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm i -g @antfu/ni
      - run: nci

      - name: Run Playwright tests
        run: nr e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: apps/e2e/playwright-report/
          retention-days: 30
